### PR TITLE
Create de.json

### PR DESCRIPTION
**Pull request by gulaschskanone**

### CODE REVIEW

**Comment by lpagliari** [comment]
@gulaschskanone did you run the frontend tests? I believe they need to be modified now that you've added de.json. Take a look on the test `"uses default values when language was not localized yet"` @ `comment_l10n.js`.

To run the tests: http://localhost:9001/tests/frontend/

**Comment by gulaschskanone** [comment]
I'm a beginner in etherpad development. The frontend tests doesn't work (310 ERR_TOO_MANY_REDIRECTS). I've no idea what I should modify in "comment_l10n.js"

**Comment by lpagliari** [comment]
what's the URL you're using to access your pads on your machine?

**Comment by gulaschskanone** [comment]
http://local.host:9001/ is right

**Comment by lpagliari** [comment]
so when you access http://local.host:9001/tests/frontend/ you get the 310 ERR_TOO_MANY_REDIRECTS?

**Comment by gulaschskanone** [comment]
unfortunately yes

**Comment by lpagliari** [comment]
Hum, never saw that on Etherpad, I guess you'll have to take a look about that issue. Sorry...

**Comment by lpagliari** [comment]
@gulaschskanone maybe this could be a start for your research: http://stackoverflow.com/a/10544999.

**Comment by lpagliari** [comment]
Sorry for the delay on accepting this, had to fix the broken test first

**Comment by gulaschskanone** [comment]
thanks a lot!

**Pull request merged**
