### PR TITLE
Accepted comments

### PR DESCRIPTION
**Pull request by JohnMcLear**
This functionality allows accepted comments to be reverted etc.  It was a bit of a pita to implement

### CODE REVIEW

**Comment by JohnMcLear** [comment]
All tests pass!

**Comment by DrHuxtable** [comment]
John, I'm not certain where best to ask this question, so please let me know if this is not the appropriate spot. Anyway, I'm curious why in the comments plugin the "comment" submit button at the bottom of the flyout is only visible on first interaction. It then seems to disappear, and the user is expected to know that a simply "enter/return" on the keyboard will work for further interaction. Is there a specific reason the "comment" or other "submit" type of a button does not persist?

**Comment by JohnMcLear** [comment]
@DrHuxtable see latest version, it's more obvious..  RE why, it's because I'm not a UI/UX guy, feel free to commit better solutions! :)

**Comment by DrHuxtable** [comment]
@JohnMcLear thank you, that is better. Initially, I just didn't want to start going down a path somebody had already been down and returned from with half a head of hair. I'll see what I can come up with. Thanks!

**Comment by lpagliari** [comment]
Wow, awesome feature!!

**Pull request merged**
