### PR TITLE
Re-submitting #43

### PR DESCRIPTION
**Pull request by lpagliari**
Re-submitting PR #43 (Fixing issues on smaller screens (<850px)), now on a clean project.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Still a huge comparison -_-

**Comment by lpagliari** [comment]
Sorry, @JohnMcLear , I don't get it. `index.js` has a lot of changes because it needed to be changes in a lot of places, but there was nothing I could do in that case. Were you expecting a smaller PR? 

Sorry about the big PR, but part of it was actually a bit tricky (move `#newComment` out of `#comments`), and affected a lot of places. If you have a better idea on how we could show `#newComment` form without displaying the other comments inside of `#comments`, I could work on that instead.

**Comment by JohnMcLear** [comment]
Take a look at https://github.com/JohnMcLear/ep_comments/pull/45/files

it doesn't seem right??

**Comment by lpagliari** [comment]
Unfortunately, that is correct. :(

Here's what was changed on each of the 8 files:

* `locales/*` + `templates/comments.html`: localization of delete button;
* `comment.css`:
  * styles for `#newComment` outside of `#comments`
  * fix for the media query that chooses whether to display comments or not;
* `index.js`:
  * creating new container for `#newComment`;
  * using functions `showNewCommentForm()` and `hideNewCommentForm()` to encapsulate code to display/hide `#newComments`;
  * using class `active` to display/hide `#comments`, instead of calling `show()`/`hide()` (otherwise user preference would be ignored in some scenarios);
* `static/tests/frontend/*`: refactored existing tests, created a new one for settings related to comments display/hide;

If you check #43, you can find the 2 scenarios I identified as incorrect, and the 3 actions I had to take to fix them.

I hope that helps...

**Comment by JohnMcLear** [comment]
Oh wow, damn I didn't know it would be that much work!  Good job!

**Pull request merged**
