### PR TITLE
Fixing issues on smaller screens (<850px)

### PR DESCRIPTION
**Pull request by lpagliari**
While testing ep_comments_page on smaller screens (<850px), I found some issues:

* If user unchecks "Show Comments" setting and clicks button to add a new comment, sidebar comments will be displayed (this also happens on larger screens);
* Sidebar comments were not being hidden on smaller screens if user checks "Show Comments" (i.e. media queries were being ignored). That could be the expected behavior (user can "force" comments to be displayed), but in this case it would not make sense to have the media queries anyway, so I thought this was an issue;

Solution included:

* moving `#newComment` out of `#comments` (and into a similar container), otherwise there would be no way (or I could not think of any) to show the #newComment form while hiding existing sidebar comments;
* replacing existing calls to `show()` by `addClass('active').removeClass('inactive')`, so media queries are useful again;
* removing code from `collectComments()` that made `#comments` always visible because we need to respect user's setting defined on "Show Comments", and this code was ignoring that;

BTW, I think 850px might be too small to limit the media query. It seems that 935px would be better, as it would make sure comments are not overlapping any text on the pad. I didn't change this specific value, but I can do it if you agree that would be better.

image

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Feel free to change to 935 :)  Looks good!

**Comment by lpagliari** [comment]
Will do. Won't be able to work on this right now, but I'll try to finish it
later today.

**Comment by JohnMcLear** [comment]
Cool, I merge the delete stuff too so you will need to rebase etc.

**Comment by lpagliari** [comment]
Used 955px instead of 935px, looked better. And after rebasing I've added l10n for the delete button -- not sure if there are other changes from the delete branch that need to be localized. If there is any, let me know and I'll adjust the pt-BR.json file.

**Comment by JohnMcLear** [comment]
Don't think so but this still can't be merged due to conflicts...

**Comment by lpagliari** [comment]
Apparently every time I rebase & fix merge conflicts, than do a git push, Github complains there are merge conflicts. Any ideas to stop having that?

On this specific PR, the conflict I had was on `comment.css`, on padding for `.sidebar-comment` (there was a trailing space removed on my commit, and yours changed that to `padding: 0px 5px 5px 5px;`).

**Comment by JohnMcLear** [comment]
hrm, not sure, I'd suggest working from branches, that makes it a lot easier to deal with..  

If you can rebase your repo that will be the best thing, it looks wildly out of sync somehow :P

**Comment by lpagliari** [comment]
OK, I'll close this one and submit a clean PR. And will work in branches from now on. What a mess... :)

**Pull request closed without merging**
