### PR TITLE
UX on touch devices: Close opened comment when user touches outside of sidebar comment or modal

### PR DESCRIPTION
**Pull request by lpagliari**
Similar to #63, but for touch events.

### CODE REVIEW

**Comment by DanielBickley** [comment]
@lpagliari, sorry to bother you, but I've got a question that you had chimed in on a month or so ago, and I'm trying to resolve. It sounds like @JohnMcLear is busy with other projects, per some of his previous communication I was cc'd on. I had previously noted that the dev ep_comments plugin seemed to throw two errors in the console regarding font-awesome fonts ONLY when minification is turned on in the main etherpad settings.json. I believe you both thought this to be related to the dev Etherpad instance or something (sorry I can't for the life of me find the previous comment on github - which is why I write to you here). Anyway, I'm trying to resolve that on my local instance, and I'm wondering if you can point me in the right direction. Maybe this is something that has already been fixed??? Do you have any workarounds or suggestions? I've got a very slow loading Etherpad, particularily in Safari (utilizing Comments and Page View), and I really need to get the minification working. I've tried some various tricks like manually placing minified versions of the two fonts that come up in the console error in a spot that looks to be where the files are trying to be located, to no avail. Any help would be appreciated, or maybe you can point me to a better spot to ask questions regarding this. Thanks!!!

**Comment by lpagliari** [comment]
@DanielBickley you probably didn't find the conversation because it was on Etherpad ploject: https://github.com/ether/etherpad-lite/pull/2690#issuecomment-111518519.

About the fix, the latest code from `develop` branch should not have the issue, there was a [PR](https://github.com/ether/etherpad-lite/pull/2707) that fixed it. If you get the latest version of Etherpad, do you still see the error when minification is on?

**Comment by DanielBickley** [comment]
@lpagliari Yep, bingo! Thank you so so very much. I really appreciate it. I found that even after the patch and turning minification back on that just Safari was still very sluggish. Turns out that sluggishness only in Safari was due to some Adware on the particular machine, and I've since removed it, retested Safari, and all is well. On to the next battle ;)

**Comment by lpagliari** [comment]
Awesome!

**Pull request merged**
